package tui

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// runInitCommand writes a CLAUDE.md scaffold to the cwd. Mirrors
// claude-code's /init: detects the project type from sentinel files
// (go.mod / package.json / Cargo.toml / pyproject.toml), extracts
// build / test commands, and assembles a markdown skeleton the user
// can edit. CLAUDE.md is the de-facto cross-tool convention (Claude
// Code, Cursor, Aider, etc. all read it), so writing it here means
// metis users can move between agents without re-documenting.
//
// Idempotency: refuses to overwrite an existing CLAUDE.md unless the
// caller passes `--force`. Returns the result message + role for
// applyREPLOutput-style display.
func runInitCommand(args string) (output, role string) {
	cwd, err := os.Getwd()
	if err != nil {
		return "init: failed to read cwd: " + err.Error(), "error"
	}
	target := filepath.Join(cwd, "CLAUDE.md")
	force := strings.Contains(args, "--force") || strings.Contains(args, "-f")

	if _, err := os.Stat(target); err == nil && !force {
		return "init: CLAUDE.md already exists at " + target +
			"\n  · pass `--force` to overwrite, or edit by hand", "warning"
	}

	pt := detectProjectType(cwd)
	body := buildClaudeMD(cwd, pt)
	if err := os.WriteFile(target, []byte(body), 0o644); err != nil {
		return "init: write failed: " + err.Error(), "error"
	}
	return fmt.Sprintf("init: wrote CLAUDE.md (%d bytes, type=%s)\n  · path: %s",
		len(body), pt.kind, target), "success"
}

// projectType captures what /init detected about the cwd. kind is the
// short label shown in the success confirmation; commands lists
// detected build / test / run lines.
type projectType struct {
	kind     string
	commands []string
	notable  []string // notable files at root (entrypoint hints)
}

// detectProjectType examines sentinel files at root to classify the
// project. Stops at the first match — projects with multiple sentinels
// (e.g. polyglot mono-repos) just show the dominant tool's hints.
func detectProjectType(dir string) projectType {
	check := func(name string) bool {
		_, err := os.Stat(filepath.Join(dir, name))
		return err == nil
	}
	switch {
	case check("go.mod"):
		return projectType{
			kind: "go",
			commands: []string{
				"`go build ./...`           — compile all packages",
				"`go test -short ./...`    — run unit tests (short mode)",
				"`go test -race ./...`     — race detector",
				"`go vet ./...`            — static analysis",
			},
			notable: rootNotables(dir, []string{"main.go", "go.mod", "go.sum", "Makefile", "README.md"}),
		}
	case check("package.json"):
		return projectType{
			kind: "node",
			commands: []string{
				"`npm install`     — install dependencies",
				"`npm run build`   — build (see scripts in package.json)",
				"`npm test`        — run tests",
			},
			notable: rootNotables(dir, []string{"package.json", "tsconfig.json", "README.md", "src", "lib"}),
		}
	case check("Cargo.toml"):
		return projectType{
			kind: "rust",
			commands: []string{
				"`cargo build`            — compile",
				"`cargo test`             — run tests",
				"`cargo clippy`           — lint",
				"`cargo fmt -- --check`   — format check",
			},
			notable: rootNotables(dir, []string{"Cargo.toml", "src", "README.md"}),
		}
	case check("pyproject.toml") || check("setup.py") || check("requirements.txt"):
		return projectType{
			kind: "python",
			commands: []string{
				"`pip install -e .`              — editable install",
				"`pytest`                        — run tests",
				"`ruff check .`                  — lint",
				"`mypy .`                        — type-check",
			},
			notable: rootNotables(dir, []string{"pyproject.toml", "setup.py", "requirements.txt", "README.md", "src"}),
		}
	}
	return projectType{kind: "unknown", commands: []string{
		"(no sentinel files detected — fill in your build/test commands here)",
	}}
}

// rootNotables returns the subset of `wanted` that actually exists at root.
func rootNotables(dir string, wanted []string) []string {
	var out []string
	for _, w := range wanted {
		if _, err := os.Stat(filepath.Join(dir, w)); err == nil {
			out = append(out, w)
		}
	}
	return out
}

// buildClaudeMD assembles the markdown skeleton. Sections are
// intentionally shallow + stub-like — the user is expected to edit the
// "Project conventions" section by hand. Header carries an `<!-- @metis -->`
// marker so future re-runs can offer to re-scan the auto-detected
// blocks while preserving the user-edited section.
func buildClaudeMD(cwd string, pt projectType) string {
	var b strings.Builder
	projName := filepath.Base(cwd)

	b.WriteString("# " + projName + "\n\n")
	b.WriteString("<!-- Auto-generated by `metis /init` on " + time.Now().Format("2006-01-02") + ". -->\n")
	b.WriteString("<!-- This file is read by Claude Code, Cursor, Aider, and other LLM agents -->\n")
	b.WriteString("<!-- as project context. Edit freely — the next `/init --force` will -->\n")
	b.WriteString("<!-- only overwrite the auto-detected sections (Build commands, Files). -->\n\n")

	b.WriteString("## Project type\n\n")
	b.WriteString("- " + pt.kind + "\n\n")

	b.WriteString("## Build / test commands\n\n")
	for _, c := range pt.commands {
		b.WriteString("- " + c + "\n")
	}
	b.WriteString("\n")

	if len(pt.notable) > 0 {
		b.WriteString("## Notable files\n\n")
		for _, f := range pt.notable {
			b.WriteString("- `" + f + "`\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Project conventions\n\n")
	b.WriteString("<!-- Edit this section. Examples: -->\n")
	b.WriteString("<!-- - Naming style (snake_case for files, PascalCase for types) -->\n")
	b.WriteString("<!-- - Commit message format (conventional commits) -->\n")
	b.WriteString("<!-- - Branching model (trunk-based / git-flow / release branches) -->\n")
	b.WriteString("<!-- - Testing requirements (unit + integration before merge) -->\n\n")

	b.WriteString("## Things NOT to touch\n\n")
	b.WriteString("<!-- Edit this section. Examples: -->\n")
	b.WriteString("<!-- - Generated code (mark with comment + path glob) -->\n")
	b.WriteString("<!-- - Vendored dependencies -->\n")
	b.WriteString("<!-- - Production secrets / config -->\n\n")

	b.WriteString("## How to ask the agent for help\n\n")
	b.WriteString("- For bug fixes: describe the symptom + minimal repro\n")
	b.WriteString("- For features: describe the user-visible behavior, not the implementation\n")
	b.WriteString("- For refactors: name the smell + the desired shape\n")

	return b.String()
}
