package tui

// word_diff.go computes intra-line character diff masks so paired
// delete/insert rows in the chat surface highlight the SPECIFIC
// changed tokens inside a line — claude-code's hot-spot
// visualization. Without this, "fmt.Println("hi")" → "fmt.Println("bye")"
// shows the entire line in red+green; with this, just `"hi"`/`"bye"`
// pop while the surrounding `fmt.Println(...)` stays dim.
//
// Algorithm: standard LCS (longest common subsequence) over rune
// arrays. O(N*M) time/space — fine for typical code lines (<200
// runes) and we cap the input length below to avoid pathological
// blow-up on autogenerated minified lines.

const wordDiffMaxLen = 400 // skip line pairs longer than this combined

// wordDiffMasks compares two strings rune-by-rune and returns two
// boolean masks of equal length to the rune-counts of `old` and `new`.
// mask[i] == true means rune i is part of the LCS (unchanged in the
// other string); false means it differs and should be highlighted.
//
// When inputs are too long, returns nil masks — caller falls back to
// whole-line highlighting.
func wordDiffMasks(old, new string) (delMask, insMask []bool) {
	a := []rune(old)
	b := []rune(new)
	if len(a)+len(b) > wordDiffMaxLen {
		return nil, nil
	}
	m, n := len(a), len(b)
	if m == 0 || n == 0 {
		// Pure add or pure remove — nothing to "highlight" since
		// every rune is a change.
		return make([]bool, m), make([]bool, n)
	}

	// dp[i][j] = LCS length of a[:i] and b[:j].
	dp := make([][]int, m+1)
	for i := range dp {
		dp[i] = make([]int, n+1)
	}
	for i := 1; i <= m; i++ {
		for j := 1; j <= n; j++ {
			if a[i-1] == b[j-1] {
				dp[i][j] = dp[i-1][j-1] + 1
			} else if dp[i-1][j] > dp[i][j-1] {
				dp[i][j] = dp[i-1][j]
			} else {
				dp[i][j] = dp[i][j-1]
			}
		}
	}

	delMask = make([]bool, m)
	insMask = make([]bool, n)
	// Backtrack: when both runes match and the length came from dp[i-1][j-1],
	// they're part of the LCS — mark both. Otherwise advance from
	// whichever side dropped a rune.
	for i, j := m, n; i > 0 && j > 0; {
		if a[i-1] == b[j-1] {
			delMask[i-1] = true
			insMask[j-1] = true
			i--
			j--
		} else if dp[i-1][j] >= dp[i][j-1] {
			i--
		} else {
			j--
		}
	}
	return delMask, insMask
}

// applyMask renders a line with per-run style switching: contiguous
// same-mask rune ranges are batched into one Render() call so we don't
// emit ANSI escapes around every character. mask[i]==true uses
// `unchanged`, false uses `changed`. Returns the styled string.
func applyMask(content string, mask []bool, unchanged, changed func(string) string) string {
	if mask == nil {
		// Fallback: no word-level info — apply 'changed' to whole.
		return changed(content)
	}
	runes := []rune(content)
	if len(runes) != len(mask) {
		// Length mismatch (shouldn't happen but defensive).
		return changed(content)
	}
	var out []byte
	i := 0
	for i < len(runes) {
		j := i + 1
		for j < len(runes) && mask[j] == mask[i] {
			j++
		}
		segment := string(runes[i:j])
		if mask[i] {
			out = append(out, []byte(unchanged(segment))...)
		} else {
			out = append(out, []byte(changed(segment))...)
		}
		i = j
	}
	return string(out)
}
