// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScheduledTask(arg1) {
  return window['go']['main']['App']['DeleteScheduledTask'](arg1);
}

export function GetCurrentModel() {
  return window['go']['main']['App']['GetCurrentModel']();
}

export function GetProjectDir() {
  return window['go']['main']['App']['GetProjectDir']();
}

export function GetScheduledTasks() {
  return window['go']['main']['App']['GetScheduledTasks']();
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function PauseScheduledTask(arg1) {
  return window['go']['main']['App']['PauseScheduledTask'](arg1);
}

export function ResumeScheduledTask(arg1) {
  return window['go']['main']['App']['ResumeScheduledTask'](arg1);
}

export function RunScheduledTask(arg1) {
  return window['go']['main']['App']['RunScheduledTask'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function StartWebUI() {
  return window['go']['main']['App']['StartWebUI']();
}
