// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseWorkspaceDirectory():Promise<string>;

export function DeleteScheduledTask(arg1:string):Promise<void>;

export function GetCurrentModel():Promise<string>;

export function GetProjectDir():Promise<string>;

export function GetScheduledTasks():Promise<Array<main.ScheduledTaskInfo>>;

export function GetSessionMessages(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSettings():Promise<string>;

export function GetUpdateStatus():Promise<main.DesktopUpdateStatus>;

export function GetVersion():Promise<string>;

export function InstallUpdateAndRestart():Promise<main.DesktopUpdateStatus>;

export function PauseScheduledTask(arg1:string):Promise<void>;

export function ResumeScheduledTask(arg1:string):Promise<void>;

export function RunScheduledTask(arg1:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<main.MessageResponse>;

export function StartWebUI():Promise<string>;
