package config

// schema.go — generate a JSON Schema from the metis Config struct so
// IDEs (VSCode, Zed, JetBrains) can offer autocomplete / hover docs /
// validation when the user edits ~/.metis/config.toml.
//
// Two generation strategies were considered:
//
//   1. invopop/jsonschema (chosen) — pure reflection over struct
//      tags. Zero per-field manual schema upkeep: the schema follows
//      the Config struct automatically as fields are added/renamed.
//      Mirrors crush's `internal/cmd/schema.go` approach.
//
//   2. Hand-written schema map — picks up toml tags via reflect, but
//      requires a switch over each field's type. Faster cold-start
//      but accumulates drift every time someone adds a config field
//      and forgets to update the schema. Rejected.
//
// claude-code-sourcemap has `utils/zodToJsonSchema.ts` (zod v4
// toJSONSchema + WeakMap cache for repeat-type dedup) but doesn't
// expose a CLI command. We borrow the cache idea (sync.Map keyed on
// reflect.Type) so a deeply-nested Config doesn't reflect the same
// embedded type N times.

import (
	"encoding/json"
	"fmt"
	"sync"

	"github.com/invopop/jsonschema"
)

// schemaCache memoises generated schemas per type so repeated
// invocations of GenerateConfigSchema don't re-reflect the same
// Config struct. Key is the runtime type pointer; value is the
// already-rendered JSON bytes. Mirrors claude-code's WeakMap-style
// type→schema caching, adapted to Go's lack of WeakMap (sync.Map
// holds strong refs but the Config type itself never gets GC'd).
var schemaCache sync.Map

// GenerateConfigSchema reflects the Config struct and returns a
// JSON Schema (draft-07) byte slice ready to write to disk. The
// schema covers all fields with `toml:"name"` tags, plus auto-
// derived field names for tagless fields (matches invopop's
// default behaviour: snake_case Go field names).
//
// Pretty-printed (2-space indent) so the on-disk file is reviewable
// in a diff. JSON-Schema $schema field is set to draft-07 — the
// most widely-supported draft across IDE language servers in 2026.
func GenerateConfigSchema() ([]byte, error) {
	const cacheKey = "Config"
	if cached, ok := schemaCache.Load(cacheKey); ok {
		if b, ok := cached.([]byte); ok {
			// Defensive copy so callers can't mutate the cache.
			out := make([]byte, len(b))
			copy(out, b)
			return out, nil
		}
	}

	r := &jsonschema.Reflector{
		// Anonymous structs (e.g. nested toml subsections) get
		// their fields lifted into the parent rather than emitted
		// as separate `$defs`. Cleaner schema for IDE consumers.
		ExpandedStruct: false,
		// AllowAdditionalProperties=true so the schema doesn't
		// reject brand-new keys when metis adds a config field
		// faster than the user's metis-installed schema gets
		// regenerated. Permissive matches TOML's read-anything ethos.
		AllowAdditionalProperties: true,
		// DoNotReference=false → invopop emits $ref for repeated
		// types (the per-channel structs share a shape pattern).
		// Smaller schema, easier for IDEs to navigate.
		DoNotReference: false,
		// FieldNameTag defaults to "json"; metis Config uses TOML
		// tags as the source of truth so override.
		FieldNameTag: "toml",
	}

	schema := r.Reflect(&Config{})
	if schema == nil {
		return nil, fmt.Errorf("config: reflect returned nil schema")
	}
	// Document the schema's purpose so a curious user opening the
	// file sees what it's for.
	schema.Title = "metis configuration"
	schema.Description = "Schema for ~/.metis/config.toml — generated by `metis config schema`."

	out, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("config: marshal schema: %w", err)
	}

	cached := make([]byte, len(out))
	copy(cached, out)
	schemaCache.Store(cacheKey, cached)
	return out, nil
}

// ResetSchemaCache clears the memoised schema. Called from tests so
// stale cache entries don't leak between table rows. Production code
// has no reason to call it; the cache holds across the process
// lifetime intentionally.
func ResetSchemaCache() {
	schemaCache = sync.Map{}
}
